### ISSUE TITLE
Issues running the explorer with the local quorum 7nodes example setup

### ISSUE THREAD

**Issue by amitakamat** [Councilbox/councilbox-quorum-explorer#17]
I have a local setup of the quorum 7nodes example running on my system. I am trying to use the cbx-quorum-explorer to connect to the nodes to access the Transactions and Blocks. When I run the app, it gets stuck on loading. I think I have incorrect values in the env.sh file.

OS : Ubuntu 18.04.1

```
QUORUM_HOST=
ENABLE_SSL=
EXPLORER_PORT=5000
API_DOMAIN=localhost
MONGO_DATA_DIR=/home/mongo
API_PORT=
EXTERNAL_API_PORT=22001
WEBAPP_VERSION=cbx
```

I am new to Quorum. Could you please help me connecting the explorer with the 7nodes example setup?

**Comment by brunneis** [comment]
Hi @amitakamat,
Try setting the `QUORUM_HOST` variable with the hostname/IP of one of those nodes. Note that the `22000` port has to be open on that node. You can check it with `telnet node_host_or_ip 22000`.

Happy to help!

**Comment by amitakamat** [comment]
Thank you for the quick response. The 7nodes example runs on localhost on ports 22000 - 22006. I can telnet and connect to the ports. 

From the Network tab on the browser, I could see that the API call `"/api/status"`(http://localhost:22001/api/status) gets called continuously with the error `"SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"` in the console. Am i missing something in the setup?

**Comment by brunneis** [comment]
It should work if you use the following `env.sh`:

```
QUORUM_HOST=localhost
ENABLE_SSL=
EXPLORER_PORT=5000
API_DOMAIN=localhost
MONGO_DATA_DIR=/home/mongo
API_PORT=
EXTERNAL_API_PORT=
WEBAPP_VERSION=cbx
```
However, since the Docker container that syncs the blockchain in a MongoDB database is isolated from the host's network, a change in the `docker-compose.yaml.template` has to be made (configure that container to use the same network as the host)

Here it is the modified file that you should use to replace the provided one:
https://gist.github.com/brunneis/f6ffc3898635f2ab5718f8ab0f5f6905

**Comment by amitakamat** [comment]
Hi @brunneis 
I tried the above changes. I still face the same issues. The homepage gets stuck on calling `"http://localhost:22001/api/status"`. I tried curl on this url and I did not get anything in response. 

When I tried `"http://localhost:8080/api/status"`, I got the response `"{"status": "UP", "node": {"status": "D", "version": "O"}}"`. My quorum nodes are running on port 22000-22006.

**Comment by amitakamat** [comment]
Ok, I tried opening the explorer in a different browser and it worked. I have the status API working and it shows up as green. But, the blocks API returns `{"type": "latest blocks", "result": {"data": []}}`.

**Comment by brunneis** [comment]
Can you paste here the logs of the `syncer` container?

You can find the `syncer` container name with `docker ps`. To print the logs just type `docker logs <container_name>`.

**Comment by amitakamat** [comment]
I do not have a syncer container running after executing the script.  

```
amita@ubuntu:~/explorer/cbx-quorum-explorer$ sudo ./launch.sh 
Creating network "cbxquorumexplorer_default" with the default driver
Creating cbxquorumexplorer_webapp_1 ... 
Creating cbxquorumexplorer_mongodb_1 ... 
Creating cbxquorumexplorer_mongodb_1
Creating cbxquorumexplorer_webapp_1 ... done
Creating cbxquorumexplorer_syncer_1 ... 
Creating cbxquorumexplorer_http-api_1 ... 
Creating cbxquorumexplorer_syncer_1
Creating cbxquorumexplorer_http-api_1 ... done
amita@ubuntu:~/explorer/cbx-quorum-explorer$ sudo docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                    NAMES
f3a829d2423f        councilbox/quorum-explorer-http-api     "gunicorn -w 8 --bin…"   4 minutes ago       Up 4 minutes        0.0.0.0:8080->8080/tcp   cbxquorumexplorer_http-api_1
bd8703c2f222        councilbox/quorum-explorer-webapp:cbx   "entrypoint.sh"          5 minutes ago       Up 4 minutes        0.0.0.0:5000->80/tcp     cbxquorumexplorer_webapp_1
80aa2192048e        mongo:4.0-xenial                        "mongod --smallfiles…"   5 minutes ago       Up 4 minutes        27017/tcp                cbxquorumexplorer_mongodb_1
```

**Comment by brunneis** [comment]
It seems it died, but it should exists. You can watch all containers (even those that are not running) with `docker ps -a`. 
The command `docker logs cbxquorumexplorer_syncer_1` should do the trick.

**Comment by amitakamat** [comment]
Thanks. I tried running the command. It gave me the below error.

```
amita@ubuntu:~/explorer/cbx-quorum-explorer$ sudo docker ps -a
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                      PORTS                    NAMES
f3a829d2423f        councilbox/quorum-explorer-http-api     "gunicorn -w 8 --bin…"   18 minutes ago      Up 18 minutes               0.0.0.0:8080->8080/tcp   cbxquorumexplorer_http-api_1
a9bfeee5f66b        councilbox/quorum-explorer-syncer       "syncer.py"              18 minutes ago      Exited (1) 17 minutes ago                            cbxquorumexplorer_syncer_1
bd8703c2f222        councilbox/quorum-explorer-webapp:cbx   "entrypoint.sh"          18 minutes ago      Up 18 minutes               0.0.0.0:5000->80/tcp     cbxquorumexplorer_webapp_1
80aa2192048e        mongo:4.0-xenial                        "mongod --smallfiles…"   18 minutes ago      Up 18 minutes               27017/tcp                cbxquorumexplorer_mongodb_1

amita@ubuntu:~/explorer/cbx-quorum-explorer$ sudo docker logs cbxquorumexplorer_syncer_1
Traceback (most recent call last):
  File "/usr/local/bin/syncer.py", line 249, in <module>
    filler = Filler()
  File "/usr/local/bin/syncer.py", line 75, in __init__
    background=True)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 1958, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 196, in _socket_for_writes
    return self.__database.client._socket_for_writes()
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1085, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb:27017: [Errno -3] Temporary failure in name resolution
```

**Comment by brunneis** [comment]
Ok, so since the MongoDB container shares the host's network it can't resolve the mongodb name managed by Docker in the network created for the docker-compose stack.

I've updated the gist of the `docker-compose.yaml.template` that you should use to replace yours: https://gist.github.com/brunneis/f6ffc3898635f2ab5718f8ab0f5f6905.

Now the MongoDB container exposes its port to the host's network and an environment variable is set un the syncer container so it will reach the MongoDB container at localhost. 

Sorry for this, I didn't take into account local executions of the Quorum node. I will update the repo after this issue is solved.

**Comment by amitakamat** [comment]
Hello @brunneis , The above fix worked for me and I can see all the blocks and transactions. Thanks! 

Just one question: If I want to connect this application to a cloud RPC endpoint, where should I put the endpoint in env.sh?

**Comment by amitakamat** [comment]
I added my endpoint to the var QUORUM_HOST and added var QUORUM_PORT and it seems to work for my cloud endpoint. The blocks are syncing but I cannot see the transactions yet.

**Comment by brunneis** [comment]
Is it working now with the remote endpoint? Transactions should get synced while processing the blocks  so maybe there aren't transactions in the first blocks.
I'll close this issue but if you still have trouble seeing the transactions feel free to open a new issue. As commented, I'll update this repo for local syncing.

If you like this project we would be very thankful if you give us a star :)
