### ISSUE TITLE
The settings don't work

### ISSUE THREAD

**Issue by colindog** [Councilbox/councilbox-quorum-explorer#22]
I set QUORUM_ENDPOINTS=http://10.50.0.2:22000 in env.sh.
And checking from docker-compose.yaml :
  syncer:
    image: councilbox/quorum-explorer-syncer
    logging: *default-logging
    environment:
      - QUORUM_ENDPOINTS=http://10.50.0.2:22000
    depends_on:
      - mongodb

But after launching the script, check the logs of explorer-syncer. The error logs are:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=22000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HT                        TPConnection object at 0x7f2e1562b7f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
 It seems the settings don't work.
Can you help to check this?

**Comment by brunneis** [comment]
If you type `curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://10.50.0.2:22000` in the command line it should output a JSON if the endpoint is accessible.

If you receive no response, the port may be closed, as it seems, in the firewall.

**Comment by colindog** [comment]
Dear brunneis,
    I can make sure that http://10.50.0.2:22000  works.
    My question is what I set in env.sh is  http://10.50.0.2:22000.
    But from the logs, what the syncer container used is still the default localhost:22000.
    The settings don't work.

**Comment by brunneis** [comment]
My wrong, I misread the logs. Let me try to replicate it.

**Comment by brunneis** [comment]
I can't replicate it in my environment. I've updated the Docker images on Dockerhub so you can try with the new images. Anyway, you can just launch the `build.sh` script before executing `launch.sh`.

- councilbox/quorum-explorer-syncer
- councilbox/quorum-explorer-http-api
- councilbox/quorum-explorer-webapp:cbx

**Comment by colindog** [comment]
Thanks.
It works well after I build the new images.
