### ISSUE TITLE
Broken link from block dashboard

### ISSUE THREAD

**Issue by ggarri** [Councilbox/councilbox-quorum-explorer#24]
When a user clicks on the block link from the dashboard it is using the wrong block id as the id was formatted in the way it is shown in the table

![image](https://user-images.githubusercontent.com/2728080/60754928-c651f600-9fe8-11e9-8a97-103c739f4311.png)

## Actual Link
https://alastria-explorer.councilbox.com/block/13,473,143

## Expected Link
https://alastria-explorer.councilbox.com/block/13473143

**Comment by brunneis** [comment]
This issue is related to outdated cached files, I cannot reproduce it.
