### ISSUE TITLE
cbx-quorum-explorer installation

### ISSUE THREAD

**Issue by dvgoyeneche** [Councilbox/councilbox-quorum-explorer#25]
I have installed cbx-quorum-explorer in a machine and I am trying to access the web server from another machine and it not works, ¿does this explorer work without using localhost?

**Comment by brunneis** [comment]
Are ports 8080 and 80 open on the machine where you installed the explorer? It does. Are you using a reverse proxy?

**Comment by dvgoyeneche** [comment]
Ports 80 and 8080 are open, there is no reverse proxy



-------- Mensaje original --------
Asunto: Re: [Councilbox/cbx-quorum-explorer] cbx-quorum-explorer installation (#25)
De: Rodrigo Martínez <notifications@github.com>
Para: Councilbox/cbx-quorum-explorer <cbx-quorum-explorer@noreply.github.com>
CC: Daniel Villanueva Goyeneche <dvillanueva@cener.com>,Author <author@noreply.github.com>


Are ports 8080 and 80 open on the machine where you installed the explorer? It does. Are you using a reverse proxy?

-

**Comment by dvgoyeneche** [comment]
In the javascript console, I get this error:
 GET http://localhost:8080/api/status net::ERR_CONNECTION_REFUSED
(anonymous) @ ServerStatus.js:23
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ServerStatus.js:23 TypeError: Failed to fetch

**Comment by dvgoyeneche** [comment]
any idea?

**Comment by brunneis** [comment]
Can you access API endpoints directly?  http://localhost:8080/api/status for instance.
