### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by dvgoyeneche** [Councilbox/councilbox-quorum-explorer#26]
We get an "Invalid Date" Datetime in the block explorer.
Also, when clicking a block number we get this javascript error:

GET http://192.168.2.140:8080/api/block?value=4095 500 (INTERNAL SERVER ERROR)

**Comment by brunneis** [comment]
Hi @dvgoyeneche, which network are you syncing? I can't replicate the error solely with that info. Thanks!

**Comment by dvgoyeneche** [comment]
My own Quorum network

**Comment by brunneis** [comment]
Could you provide the logs of the HTTP API container? (`docker logs`)

**Comment by dvgoyeneche** [comment]
2020-04-29 20:49:41 [ERROR] Metrics/f345eb4e3e18 â exception raised when executing the loop: process_blocks
Traceback (most recent call last):
  File "/opt/catenae/catenae/link.py", line 287, in _loop_task
    target(*args, **kwargs)
  File "./metrics.py", line 46, in process_blocks
    self.update_monthly_txs(timestamp, txs_no)
  File "./metrics.py", line 61, in update_monthly_txs
    month_id = Metrics.get_month_id(timestamp)
  File "./metrics.py", line 53, in get_month_id
    date = datetime.datetime.fromtimestamp(timestamp)
OSError: [Errno 75] Value too large for defined data type

**Comment by dvgoyeneche** [comment]
![image](https://user-images.githubusercontent.com/49909762/80646079-61322a00-8a6c-11ea-988f-2785e962f4ed.png)

**Comment by dvgoyeneche** [comment]
![image](https://user-images.githubusercontent.com/49909762/80647806-5af17d00-8a6f-11ea-958b-312f8b3f4804.png)

**Comment by dvgoyeneche** [comment]
eth.getBlock(18627)
{
  difficulty: 131072,
  extraData: "0x0000000000000000000000000000000000000000000000000000000000000000f84432b84144a7b129ed84f84f1cf3be41ee2ddfa28297817b21e69bbb4a2a7c97e516b86b6a58c4d4dd5f02d0e0019946c9836d7f58ba1b708b7202df9097677314dfd1ca01",
  gasLimit: 1300233887,
  gasUsed: 140418,
  hash: "0x6c8aab5eb9126ec9c79cc99d81899133b33d07932a673c724e451a4ca331ff37",
  logsBloom: "0x00000000000000000000000000000000000000004000000000040400000000000000000000000000000000000000000000000000000000020000000000000000200000000000000000000000000000200000000200000000000000000000000000800000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 18627,
  parentHash: "0x5b02fa91c93c4d3c76eec85da0efbd04250c10e686c8e34aae197d306c7b2f2e",
  receiptsRoot: "0x214e9b87b298d05049f8778947175407dfb084949ffb1c0531a37af05cad14a1",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 858,
  stateRoot: "0x9466b30a029d6f547120f11a1472adceef028505c8a852cc24f9c4d4d793f536",
  timestamp: 1588192632723338800,
  totalDifficulty: 2441478144,
  transactions: ["0x0870238ada3a0fc96b76196609819bf90b936febf9c19583b25735109682c5c8"],
  transactionsRoot: "0x1d82c9d92dc6a9113f630ffd32c5deaa7353f19e7d63a21f9bf26624b1766f2f",
  uncles: []
}

**Comment by dvgoyeneche** [comment]
clicking in a block number, we get (internal server error)

rlp: expected input list for []common.Address, decoding into (*types.IstanbulExtra)(struct { Validators []common.Address; Seal []uint8; CommittedSeal [][]uint8 }).Validators
2020-04-30 08:02:53 [ERROR] Exception on /api/block [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/docker/services/blocks.py", line 53, in get
    block = get_clean_block(block, self.extra_data_format)
  File "/opt/docker/services/utils.py", line 34, in get_clean_block
    block['vanity'] = extraData['vanity']
TypeError: 'NoneType' object is not subscriptable
